### ISSUE TITLE
Support webpack 5

### ISSUE THREAD

**Issue by raimund-schluessler** [vue-styleguidist/vue-styleguidist#1074]
**Current behavior**

After upgrading to our app to webpack5 https://github.com/nextcloud/nextcloud-vue/pull/1781, `vue-styleguidist build` fails with the following output:
```sh
Building style guide ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■    92%(node:70115) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
Building style guide ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 99%TypeError: message.split is not a function
    at formatMessage (/var/www/nextcloud/apps/nextcloud-vue/node_modules/react-dev-utils/formatWebpackMessages.js:18:23)
    at Array.map (<anonymous>)
    at formatWebpackMessages (/var/www/nextcloud/apps/nextcloud-vue/node_modules/react-dev-utils/formatWebpackMessages.js:106:39)
    at /var/www/nextcloud/apps/nextcloud-vue/node_modules/vue-styleguidist/lib/scripts/binutils.js:98:58
    at Hook.eval [as callAsync] (eval at create (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at emitRecords.err (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:468:23)
    at Compiler.emitRecords (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:846:39)
    at emitAssets.err (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:460:11)
    at hooks.afterEmit.callAsync.err (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:828:14)
    at eval (eval at create (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at compiler.hooks.afterEmit.tapAsync (/var/www/nextcloud/apps/nextcloud-vue/node_modules/stylelint-webpack-plugin/dist/linter.js:65:7)
    at Hook.eval [as callAsync] (eval at create (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at asyncLib.forEachLimit.err (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:825:27)
    at /var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/neo-async/async.js:2818:7
    at done (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/neo-async/async.js:3522:9)
    at alreadyWritten (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:668:8)
    at outputFileSystem.readFile (/var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/lib/Compiler.js:756:19)
    at /var/www/nextcloud/apps/nextcloud-vue/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

The main reason for the failure seems to be `TypeError: message.split is not a function`. A similar problem was also reported for react-styleguidist: https://github.com/styleguidist/react-styleguidist/issues/1703. Maybe this helps finding the reason for the problem.

**Comment by elevatebart** [comment]
Hello @raimund-schluessler ,

You are absolutely right. You are experiencing the same issue as in react-styleguidist.
It makes sense since vue-styleguidist is mostly built as an add-on on top of react-styleguidist.

Since this was partially solved in 11.1.2 of RSG, the last version of vue-styleguidist should contain the fix.

What version are you using now?

**Comment by raimund-schluessler** [comment]
> What version are you using now?

Sorry that I forgot to report the version. It is the latest available, v4.36.1.

Maybe it is because of this upstream issue https://github.com/facebook/create-react-app/pull/7929 mentioned in https://github.com/styleguidist/react-styleguidist/pull/1707

**Comment by pavelmash** [comment]
I also have a similar issue after migrate my app to webpack5

**Comment by raimund-schluessler** [comment]
Still a problem with ~v4.37.1~ ~4.38.0~ 4.40.0.

**Comment by skjnldsv** [comment]
> > What version are you using now?
> 
> Sorry that I forgot to report the version. It is the latest available, v4.36.1.
> 
> Maybe it is because of this upstream issue [facebook/create-react-app#7929](https://github.com/facebook/create-react-app/pull/7929) mentioned in [styleguidist/react-styleguidist#1707](https://github.com/styleguidist/react-styleguidist/pull/1707)

Upstream is merged

**Comment by elevatebart** [comment]
Thank you @skjnldsv 

I'll see if I need to update rsg and push the update to me.
Give me 2 hours.

**Comment by elevatebart** [comment]
@skjnldsv this does not seem to have been merged but closed...(abandonned)
I will look into what their conclusion was. Maybe some help is in there.

**Comment by elevatebart** [comment]
Found this PR actually being merged at the end of the one linked.
This looks like FaceBook engineering...

https://github.com/facebook/create-react-app/pull/10961

**Comment by elevatebart** [comment]
It does not seem to have been delivered yet

**Comment by elevatebart** [comment]
https://github.com/facebook/create-react-app/pull/10961#issuecomment-850245654

**Comment by mazhewei** [comment]
Is there any progress on this issue?

**Comment by skjnldsv** [comment]
Bump! 
5.0.0 is now released
https://github.com/facebook/create-react-app/releases/tag/v5.0.0

**Comment by skjnldsv** [comment]
@elevatebart anything we can do to help here? :)

**Comment by elevatebart** [comment]
Here is an attempt at fixing this issue.
I will deliver before the day is done, hope it helps.

**Comment by skjnldsv** [comment]
@elevatebart thanks, it doesn't seems to work for my part.
Do you have a basic demo on hand about webpack that I could use?

This is what I get
```js
ReferenceError: process is not defined
./node_modules/react-dev-utils/webpackHotDevClient.js
.@nextcloud/vue/node_modules/react-dev-utils/webpackHotDevClient.js:63
  60 | var connection = new WebSocket(
  61 |   url.format({
  62 |     protocol: window.location.protocol === 'https:' ? 'wss' : 'ws',
> 63 |     hostname: process.env.WDS_SOCKET_HOST || window.location.hostname,
  64 |     port: process.env.WDS_SOCKET_PORT || window.location.port,
  65 |     // Hardcoded in WebpackDevServer
  66 |     pathname: process.env.WDS_SOCKET_PATH || '/sockjs-node',

View compiled
__webpack_require__
.@nextcloud/vue/webpack/bootstrap:24
  21 | 	var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  22 | 	__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  23 | 	module = execOptions.module;
> 24 | 	execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
     | ^  25 | } catch(e) {
  26 | 	module.error = e;
  27 | 	throw e;

View compiled
(anonymous function)
.@nextcloud/vue/webpack/startup:4
  1 | // module cache are used so entry inlining is disabled
  2 | // startup
  3 | // Load entry module and return exports
> 4 | __webpack_require__("./node_modules/react-dev-utils/webpackHotDevClient.js");
  5 | __webpack_require__("./styleguide/global.requires.js");
  6 | __webpack_require__("./styleguide/assets/icons.css");
  7 | __webpack_require__("./styleguide/assets/additional.scss");

View compiled
(anonymous function)
http://localhost:6060/build/main.bundle.js:221569:12
```

**Comment by dominik-bln** [comment]
Should Webpack 5 be working with `v4.44.18` or is the fix not released yet? With the above version we are still seeing:


```bash
node --trace-deprecation ./node_modules/.bin/vue-cli-service styleguidist
ℹ ｢wds｣: Project is running at http://localhost:6060/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/horbd/Projects/alpha/alpha/frontend/public

You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.178.72:6060/

Compiling ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■    93%(node:32276) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation..
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at /Users/horbd/Projects/alpha/alpha/frontend/node_modules/mini-html-webpack-plugin/index.js:27:33
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dominik-bln** [comment]
Looking into this further, the used version of `mini-html-webpack-plugin` in version `2.2.1` is only compatible with Webpack 3 and 4. Version `3.x` supports Webpack 4 and higher.

```bash
npm ls mini-html-webpack-plugin                                
alpha-frontend@1.0.0 /Users/horbd/Projects/alpha/alpha/frontend
└─┬ vue-cli-plugin-styleguidist@4.44.18
  └─┬ vue-styleguidist@4.44.18
    ├── mini-html-webpack-plugin@2.2.1
    └─┬ react-styleguidist@11.2.0
      └── mini-html-webpack-plugin@3.1.3
```

**Comment by elevatebart** [comment]
Can you make a PR updating that version?

**Comment by elevatebart** [comment]
I made one, if everything is green, I'll publish a patch

**Comment by elevatebart** [comment]
Patch should come in within 10 min. @dominik-bln if you have time to test it out, you would be my hero of the month.

**Comment by skjnldsv** [comment]
> Patch should come in within 10 min. @dominik-bln if you have time to test it out, you would be my hero of the month.

For me I still get `ReferenceError: process is not defined` when doing `vue-styleguidist server`

And when building: `message.split is not a function`
```js
Building style guide ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 99%
TypeError: message.split is not a function
    at formatMessage (/home/admin/git/nextcloud-vue/node_modules/react-dev-utils/formatWebpackMessages.js:18:23)
    at Array.map (<anonymous>)
    at formatWebpackMessages (/home/admin/git/nextcloud-vue/node_modules/react-dev-utils/formatWebpackMessages.js:106:39)
    at /home/admin/git/nextcloud-vue/node_modules/vue-styleguidist/lib/scripts/binutils.js:98:58
    at Hook.eval [as callAsync] (eval at create (/home/admin/git/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/admin/git/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /home/admin/git/nextcloud-vue/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/home/admin/git/nextcloud-vue/node_modules/webpack/lib/Compiler.js:906:5)
    at /home/admin/git/nextcloud-vue/node_modules/webpack/lib/Compiler.js:490:11
    at /home/admin/git/nextcloud-vue/node_modules/webpack/lib/Compiler.js:872:14
    at Hook.eval [as callAsync] (eval at create (/home/admin/git/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/admin/git/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /home/admin/git/nextcloud-vue/node_modules/webpack/lib/Compiler.js:869:27
    at /home/admin/git/nextcloud-vue/node_modules/neo-async/async.js:2818:7
    at done (/home/admin/git/nextcloud-vue/node_modules/neo-async/async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (/home/admin/git/nextcloud-vue/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)

```

**Comment by dominik-bln** [comment]
I'm seeing basically the same.

This issue looks like it describes a similar problem: https://github.com/facebook/create-react-app/issues/9880

**Comment by dominik-bln** [comment]
As far as I can tell a fix for this problem was released in `react-dev-utils@v12.0.0`, but not sure what other breaking changes that includes. There only seems to be the overall changelog for `create-react-app@v5`.

**Comment by elevatebart** [comment]
I am on vacation until next Tuesday but I can look at a pr if you make one.

**Comment by elevatebart** [comment]
I just noticed vsg is still using version 11 or react-dev-utils. If v12 is compatible with webpack 4 it would be the solution

**Comment by dominik-bln** [comment]
I'll try to take a look at it, but since I'm not familiar with the codebase I won't make any promises just yet.

Thank you for your time and enjoy your vacation.

**Comment by dominik-bln** [comment]
With `v4.44.22` I'm now getting:

```
> vue-cli-service styleguidist
 FAIL  Failed to compile

Conflict: Multiple assets emit different content to the same filename index.html
No issues found.
```

**Comment by elevatebart** [comment]
Can you share your package.json and your vue.config.js?

**Comment by dominik-bln** [comment]
Sure, here they are:

```javascript
const path = require('path')
const webpack = require('webpack')

function resolve (dir) {
  return path.join(__dirname, '.', dir)
}

let STATIC_FILES_SUBDIR = ''
if (process.env.STATIC_FILES_SUBDIR) {
  STATIC_FILES_SUBDIR = process.env.STATIC_FILES_SUBDIR
}
const OUTPUT_PATH = 'static' + STATIC_FILES_SUBDIR

module.exports = {
  assetsDir: OUTPUT_PATH,
  configureWebpack: () => {
    return {
      resolve: {
        extensions: ['.js', '.vue', '.json', '.gql', '.ts'],
        alias: {
          vue$: 'vue/dist/vue.esm.js',
          '@': resolve('src'),
        },
        fallback: {
          crypto: require.resolve('crypto-browserify'),
          path: require.resolve('path-browserify'),
          stream: require.resolve('stream-browserify'),
          fs: false,
        },
      },
      output: {
        assetModuleFilename: `${OUTPUT_PATH}/[hash][ext][query]`,
      },
      plugins: [
        // vuetify-loader is added here automatically by vue-cli-plugin-vuetify if installed
        //
        // restrict moment.js to load only required languages
        new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /de|en|ja/),
      ],
    }
  },
  chainWebpack: config => {
    config.devtool('source-map')

    // GraphQL Loader
    config.module
      .rule('graphql')
      .test(/\.gql$/)
      .use('graphql-tag/loader')
      .loader('graphql-tag/loader')
      .end()

    // pdf.js v2.0.943 expects workerSrc to be set explicitly. Without this
    // it throws a Warning: Setting up fake worker.
    // https://github.com/mozilla/pdf.js/issues/7612
    config.module
      .rule('pdfWorker')
      .test(/pdf\.worker(\.min)?\.js$/)
      .type('asset/resource')
      .end()
  },
  css: {
    // Enable CSS source maps.
    sourceMap: true,
    extract: {
      // We cannot rely on CSS order due to Webpack Code Splitting anyways and need
      // to ensure our styles are specific through good scoping. Therefore disable
      // the annoying order warnings during builds.
      // See: https://github.com/webpack-contrib/mini-css-extract-plugin#remove-order-warnings
      ignoreOrder: true,
    },
    loaderOptions: {
      css: {
        // allow importing from CSS to JS
        importLoaders: 1,
        modules: {
          mode: 'icss',
        },
      },
    },
  },
  // eslint-loader will emit lint errors as warnings
  lintOnSave: 'warning',
  // Configure Webpack's dev server.
  // https://cli.vuejs.org/guide/cli-service.html
  devServer: {
    client: {
      logging: 'info',
    },
    host: '0.0.0.0',
    // HTTPS is needed for ASCN to work with a staging backend
    // TODO: The following line should eventually be replaced by
    // TODO: server: process.env.LOCAL_HTTPS_ENABLED === 'true' ? 'https' : 'http'
    // TODO: However, at the moment, vue-cli configures a wrong websocket-url for HMR if we do that
    // TODO: Until then, we have to keep this option
    https: process.env.LOCAL_HTTPS_ENABLED === 'true',
    allowedHosts: 'all',
    headers: {
      // inject the configuration as a cookie as described in:
      // http://read.humanjavascript.com/ch12-settings-and-configs.html
      'Set-Cookie': 'config=' + JSON.stringify({
        ascnDomain: process.env.ASCN_DOMAIN,
        apiUrl: process.env.API_URL,
        authUrl: process.env.AUTH_URL,
        boxApiEnabled: process.env.BOX_API_ENABLED === 'true',
        bulkDownloadUrl: process.env.BULK_DOWNLOAD_URL,
        debug: true,
        environmentName: process.env.ENVIRONMENT_NAME,
        matomoEnabled: process.env.MATOMO_ENABLED === 'true',
        matomoSiteId: process.env.MATOMO_SITE_ID,
        restUrl: process.env.REST_URL,
        sentryDsn: process.env.SENTRY_DSN,
        sentryEnabled: process.env.SENTRY_ENABLED === 'true',
        websocketUrl: process.env.WEBSOCKET_URL,
      }),
    },
  },
}
```

```json
{
  "name": "alpha-frontend",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "author": "",
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "NODE_ENV=production node --max_old_space_size=4096 node_modules/.bin/vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "test:unit-debug": "node --inspect --expose-gc node_modules/.bin/vue-cli-service test:unit --no-cache --runInBand --logHeapUsage",
    "lint": "vue-cli-service lint --max-warnings=0",
    "generate-possible-types": "BABEL_ENV=script babel-node bin/generatePossibleTypes.js",
    "lint:sass": "sass-lint-vue src/",
    "lint:architecture": "depcruise -c .dependency-cruiser.js --output-type err-long src/",
    "prod": "NODE_ENV=production vue-cli-service serve",
    "styleguide": "vue-styleguidist server",
    "styleguide:build": "NODE_ENV=production vue-styleguidist build",
    "test:module": "npm run test:unit -- --watch --collectCoverageFrom=\"[\\\"src/modules/$npm_package_config_testModule/**/*.{js,ts,vue}\\\"]\" --coverage ./src/modules/$npm_package_config_testModule/",
    "test:watch": "vue-cli-service test:unit --watchAll"
  },
  "dependencies": {
    "@apollo/client": "3.0.2",
    "@azure/msal-browser": "2.22.1",
    "@devmobiliza/videojs-vimeo": "0.6.0",
    "@fontsource/indie-flower": "4.5.3",
    "@fontsource/open-sans": "4.5.6",
    "@sentry/tracing": "6.18.2",
    "@sentry/vue": "6.18.2",
    "@shopify/draggable": "1.0.0-beta.12",
    "@uppy/core": "2.1.6",
    "@uppy/file-input": "2.0.5",
    "@uppy/thumbnail-generator": "2.1.1",
    "@uppy/tus": "2.2.0",
    "@videojs/themes": "1.0.1",
    "@vimeo/player": "2.16.4",
    "@websanova/vue-auth": "4.1.12",
    "axios": "0.26.1",
    "barcoder": "2.0.1",
    "clientconfig": "1.1.1",
    "content-disposition": "0.5.4",
    "core-js": "3.19.3",
    "crypto-browserify": "3.12.0",
    "flag-icon-css": "4.1.7",
    "fold-to-ascii": "5.0.0",
    "franc-min": "5.0.0",
    "graphql": "15.8.0",
    "graphql-tag": "2.12.6",
    "html2plaintext": "2.1.4",
    "i18n-iso-countries": "7.3.0",
    "immer": "9.0.12",
    "lodash": "4.17.21",
    "lozad": "1.16.0",
    "material-design-icons-iconfont": "6.5.0",
    "moment": "2.29.1",
    "papaparse": "5.3.1",
    "path-browserify": "1.0.1",
    "pdfjs-dist": "2.6.347",
    "portal-vue": "2.1.7",
    "pretty-bytes": "5.6.0",
    "qs": "6.10.3",
    "stream-browserify": "3.0.0",
    "sweetalert2": "11.3.10",
    "tiff.js": "1.0.0",
    "tiptap": "1.32.2",
    "tiptap-extensions": "1.35.2",
    "uuid": "8.3.2",
    "v-tooltip": "2.1.3",
    "video.js": "7.17.0",
    "videojs-contrib-quality-levels": "2.1.0",
    "videojs-http-source-selector": "1.1.6",
    "videojs-youtube": "2.6.1",
    "vue": "2.6.14",
    "vue-apollo": "3.1.0",
    "vue-class-component": "7.2.6",
    "vue-clipboard2": "0.3.3",
    "vue-i18n": "8.26.8",
    "vue-matomo": "4.1.0",
    "vue-observe-visibility": "1.0.0",
    "vue-router": "3.5.3",
    "vue-toasted": "1.1.28",
    "vuedraggable": "2.24.3",
    "vuelidate": "0.7.7",
    "vuetify": "2.6.4",
    "vuex": "3.6.2",
    "websocket-as-promised": "2.0.1"
  },
  "devDependencies": {
    "@babel/core": "7.17.7",
    "@babel/node": "7.16.8",
    "@types/jest": "27.4.0",
    "@types/vuelidate": "0.7.15",
    "@typescript-eslint/eslint-plugin": "5.15.0",
    "@typescript-eslint/parser": "5.15.0",
    "@vue/cli-plugin-babel": "5.0.3",
    "@vue/cli-plugin-eslint": "5.0.3",
    "@vue/cli-plugin-typescript": "5.0.3",
    "@vue/cli-plugin-unit-jest": "5.0.3",
    "@vue/cli-service": "5.0.3",
    "@vue/eslint-config-typescript": "9.1.0",
    "@vue/test-utils": "1.3.0",
    "@vue/vue2-jest": "27.0.0-alpha.4",
    "babel-eslint": "10.1.0",
    "babel-plugin-require-context-hook": "1.0.0",
    "cross-fetch": "3.1.5",
    "deep-keys": "0.5.0",
    "dependency-cruiser": "11.4.0",
    "eslint": "7.32.0",
    "eslint-config-standard": "16.0.3",
    "eslint-plugin-graphql": "4.0.0",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jest": "25.7.0",
    "eslint-plugin-lodash": "7.4.0",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "5.2.0",
    "eslint-plugin-standard": "4.1.0",
    "eslint-plugin-vue": "8.5.0",
    "hygen": "6.1.5",
    "jest": "27.5.1",
    "jest-junit": "13.0.0",
    "jest-transform-graphql": "2.1.0",
    "jest-websocket-mock": "2.3.0",
    "mock-socket": "9.1.2",
    "msw": "0.38.2",
    "sass": "1.32.13",
    "sass-lint-vue": "0.4.0",
    "sass-loader": "12.6.0",
    "semver": "7.3.5",
    "ts-jest": "27.1.3",
    "typescript": "4.5.5",
    "vue-cli-plugin-styleguidist": "4.44.22",
    "vue-cli-plugin-vuetify": "2.4.8",
    "vue-template-compiler": "2.6.14",
    "vuetify-loader": "1.7.3"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead",
    "not ie <= 11"
  ],
  "config": {
    "testModule": "**"
  },
  "engines": {
    "node": "16.14.2",
    "npm": "8.4.1"
  },
  "moduleRoots": [
    "./",
    "./src",
    "./test"
  ]
}
```

Let me know if I can do anything further to debug this.

**Comment by elevatebart** [comment]
@dominik-bln The first thing to fix is your script:

Since you ar using the vue-cli, you will need a bit of the magic to make it work:

- instead of `vue-stylebuidlst serve` use `vue-cli-service styleguidist`
- instead of `vue-stylebuidlst build` use `vue-cli-service styleguidist:build`

This should help a little bit.

**Comment by elevatebart** [comment]
I also pushed a new version just now, tell me if this helps.

Thank you for your patience.

**Comment by dominik-bln** [comment]
Thanks, that got us a little bit further I believe. There are still some errors in the browser that look unrelated to our configuration though:

<img width="1332" alt="Screenshot 2022-03-28 at 09 58 09" src="https://user-images.githubusercontent.com/855119/160370249-591338fc-32be-4c34-9d42-594a275cf341.png">

Here is our `styleguid.config.js` just in case:

```javascript
const path = require('path')

module.exports = {
  title: 'ALPHA Components',
  components: 'src/**/[A-Z]*.vue',
  assetsDir: './public',
  require: [
    path.join(__dirname, 'styleguide/global.requires.js'),
  ],
  ignore: [
    'src/App.vue',
    'src/**/*Page.vue',
    'src/**/*Query.vue',
  ],
  renderRootJsx: path.join(__dirname, 'styleguide/styleguide.root.js'),
  styleguideDir: 'dist/styleguide',
  pagePerSection: false,
  usageMode: 'collapse',
  exampleMode: 'collapse',
  skipComponentsWithoutExample: true,
  ribbon: {
    text: 'ALPHA Gitlab',
    url: '<<Omitted>>',
  },
  sections: [
    {
      name: 'Shareboards',
      components: 'src/modules/shareboard/**/[A-Z]*.vue',
    },
    {
      name: 'Artists',
      components: 'src/modules/artistHub/**/[A-Z]*.vue',
    },
    {
      name: 'All Components',
      components: 'src/**/[A-Z]*.vue',
    },
  ],
}
```

@skjnldsv Could you maybe also test again if you are seeing the same issues with the new version?

**Comment by raimund-schluessler** [comment]
@dominik-bln @skjnldsv I just tested it with webpack 5.70.0 and styleguidist 4.44.27 and it seems to run fine now. See this PR https://github.com/nextcloud/nextcloud-vue/pull/1781 and the corresponding build https://deploy-preview-1781--nextcloud-vue-components.netlify.app/

**Comment by elevatebart** [comment]
@dominik-bln what you see is another issue that seems to be happening for some customizations.

You should follow #1158 to see progress on it.

I will to try and come around to it but React is not all fun and games.
If you know react well, or knows someone who does I would be happy to explain to them what this does.

Thank you though.

**Comment by dominik-bln** [comment]
Thank you too for your quick responses and great work here. I'll follow the other issue to see if I can figure out a way to get this to work.

**Comment by skjnldsv** [comment]
@elevatebart it seems we can now build fine, but serve is still broken.
```
12:26:39.721 webpackHotDevClient.js:63 Uncaught ReferenceError: process is not defined
    at Object../node_modules/react-dev-utils/webpackHotDevClient.js (webpackHotDevClient.js:63)
    at __webpack_require__ (bootstrap:24)
    at startup:4
    at startup:9
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:63
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:4
(anonymous) @ startup:9

12:26:40.903 VM74:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1)
4043 @ VM74:2
r @ VM74:2
8048 @ VM74:2
r @ VM74:2
8641 @ VM74:2
r @ VM74:2
(anonymous) @ VM74:2
(anonymous) @ VM74:2
(anonymous) @ VM74:2
e.onload @ index.js:1
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
load (async)
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise.then (async)
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:4
(anonymous) @ startup:9
```

**Comment by skjnldsv** [comment]
I found a fix, PR incoming 
https://github.com/vue-styleguidist/vue-styleguidist/pull/1308
