### ISSUE TITLE
An error occurred while using DocGen to generate JSX's doc in a vite project

### ISSUE THREAD

**Issue by greper** [vue-styleguidist/vue-styleguidist#1088]
## step:
* create a vite project
* add vueJsx plugin in vite.config.js 
* write a jsx component `/src/components/jsx-test.jsx`
* run  `npm run dev`  , All Is Normal!
*  add vue-docgen-cli  and add npm script  `"docgen": "vue-docgen -c docgen.config.js"`
* run  `npm run docgen`
* will get error

```
npm run docgen

> docgen-test@0.0.0 docgen
> vue-docgen -c docgen.config.js

(node:20776) UnhandledPromiseRejectionWarning: Error: Error parsing D:\Codes\fast-crud\docgen-test\src\components\jsx-test.jsx for @requires tags: Unterminated regular expression (9:27)
    at D:\Codes\fast-crud\docgen-test\node_modules\vue-docgen-cli\lib\getSources.js:135:27
    at step (D:\Codes\fast-crud\docgen-test\node_modules\vue-docgen-cli\lib\getSources.js:63:23)
    at Object.throw (D:\Codes\fast-crud\docgen-test\node_modules\vue-docgen-cli\lib\getSources.js:44:53)
    at rejected (D:\Codes\fast-crud\docgen-test\node_modules\vue-docgen-cli\lib\getSources.js:36:65)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

How to support JSX in a Vite project without webapck ?

## Here is the minimum example  
https://github.com/greper/docgen-test

**Comment by elevatebart** [comment]
Thanks @greper

Yep, sorry... I think I should probably at least check the extension of the file I parse:

https://github.com/vue-styleguidist/vue-styleguidist/blob/d3e873c4d50ce71eb5a3fcaace5571994a7ef5f3/packages/vue-docgen-cli/src/getSources.ts#L59-L64

**Comment by elevatebart** [comment]
If you have time to make a quick PR, that would expedite the fix.
If not I might get on it this week-end.

Thank you again for finding it.
