### ISSUE TITLE
Vue packages version mismatch on vue-template-compiler

### ISSUE THREAD

**Issue by JBarwick89** [vue-styleguidist/vue-styleguidist#1380]
**Current behavior**

**To reproduce**

Attempting to get our application on the vue3 migration build, and styleguidist seems to be holding it back

using these package versions
```    
	"vue": "3.1.0",
    "vue-loader": "15.10.0",
    "@vue/compat": "3.1.0",
    "vue-docgen-api": "^4.52.0",
    "vue-styleguidist": "4.48.0",
    "vue-template-compiler": "2.7.7",
    "@vue/compiler-sfc": "3.1.0",
```

I get this error when attempting build the styleguide:
```
Building style guide                                          0%Error: 

Vue packages version mismatch:

- vue@3.1.0 (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue/index.js)
- vue-template-compiler@2.7.7 (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

Error: 

Vue packages version mismatch:

- vue@3.1.0 (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue/index.js)
- vue-template-compiler@2.7.7 (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-template-compiler/index.js:10:9)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadFromContext (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js:30:10)
    at loadTemplateCompiler (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js:37:12)
    at exports.resolveCompiler (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js:25:23)
    at VueLoaderPlugin.apply (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/plugin-webpack4.js:91:22)
    at webpack (/Users/jbarwick/vidyard/ConstructionYard/node_modules/webpack/lib/webpack.js:51:13)
    at build (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/scripts/build.js:15:34)
    at Object.commandBuild (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/scripts/binutils.js:91:40)
    at runIt (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin/styleguidist.js:92:16)
    at Object.<anonymous> (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin/styleguidist.js:74:5)
error Command failed with exit code 1.
```

My understanding was that `vue-template-compiler` was no longer needed, but it appears that is not the case?

**Comment by elevatebart** [comment]
Hello @JBarwick89 ,

At first glance: If you use vue 3, you should not have vue-template-compiler installed at all.
If you do, it will conflict will all web pack tooling.
Try removing that line if you can and run the install again. Then VSG should work fine.
If you can't, please explain why here.

I can't diagnose what is happening here precisely as there are a lot of constraints to each project.
I would be happy to look at concrete reproduction repository and hopefully fix the bug for your use case.

I hope you understand.

**Comment by JBarwick89** [comment]
Hey @elevatebart 
This is what I get if i don't have 'vue-template-compiler` installed.

Error seems to be coming from `vue-styleguidist`?

There is no reference or usage of `vue-template-compiler` in our `webpack.config.cjs` or `styleguide.config.cjs`

```
Building style guide                                          0%Error: Cannot find module 'vue-template-compiler'
Require stack:
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/plugin-webpack4.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/plugin.js
- /Users/jbarwick/vidyard/ConstructionYard/webpack.config.cjs
- /Users/jbarwick/vidyard/ConstructionYard/styleguide.config.cjs
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/scripts/config.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin/styleguidist.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin.js
Error: Cannot find module 'vue-template-compiler'
Require stack:
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/plugin-webpack4.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/plugin.js
- /Users/jbarwick/vidyard/ConstructionYard/webpack.config.cjs
- /Users/jbarwick/vidyard/ConstructionYard/styleguide.config.cjs
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/scripts/config.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin/styleguidist.js
- /Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at loadFromContext (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js:30:26)
    at loadTemplateCompiler (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js:37:12)
    at exports.resolveCompiler (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/compiler.js:25:23)
    at VueLoaderPlugin.apply (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-loader/lib/plugin-webpack4.js:91:22)
    at webpack (/Users/jbarwick/vidyard/ConstructionYard/node_modules/webpack/lib/webpack.js:51:13)
    at build (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/scripts/build.js:16:10)
    at Object.commandBuild (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/scripts/binutils.js:95:40)
    at runIt (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin/styleguidist.js:92:16)
    at Object.<anonymous> (/Users/jbarwick/vidyard/ConstructionYard/node_modules/vue-styleguidist/lib/bin/styleguidist.js:74:5)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
```

**Comment by elevatebart** [comment]
For vue 3, you have to update the vue-loader to 16 or above.
Version 15 is for vue2 only.

How could I have missed that...

Sorry

**Comment by JBarwick89** [comment]
> For vue 3, you have to update the vue-loader to 16 or above. Version 15 is for vue2 only.
> 
> How could I have missed that...
> 
> Sorry

wow, yup that was it! thanks!
