### ISSUE TITLE
Getting an error rendering components after upgrading to Vue 2.7: TypeError: B is not a function     at PreviewAsync

### ISSUE THREAD

**Issue by JBarwick89** [vue-styleguidist/vue-styleguidist#1384]
**Current behavior**

**To reproduce**
I'm getting this error on attempting to render all of our components in vue-styleguidist.

Error is occurring in the React preview.js code: https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/src/client/rsg-components/Preview/PreviewAsync.js#L171

<details>
<summary>Full stack trace is</summary>

```
TypeError: B is not a function
    at PreviewAsync (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2611817)
    at PreviewWithComponent
    at div
    at div
    at PlaygroundRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2615852)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at PlaygroundAsync (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2621181)
    at article
    at ExamplesRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2622060)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at Examples (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2622386)
    at div
    at ReactComponentRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2597937)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at ReactComponent (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2603657)
    at VsgReactComponent (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2606690)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at div
    at ComponentsRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2622933)
    at Components (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2623081)
    at section
    at SectionRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2623493)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at Section (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2624219)
    at section
    at SectionsRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2624931)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at Sections (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2625192)
    at main
    at div
    at StyleGuideRenderer (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2592435)
    at _class (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2527716)
    at StyleGuide (https://cy.vidyard.com/main/build/bundle.de605d09.js:2:2628313)
 ```

</details>

We recently upgraded to Vue 2.7 and to a newer version of vue styleguidist (4.50.0).

Are there other dependencies that should have been updated with that?

our `styleguide.config.cjs` is:

<details>
<summary>styleguide.config.cjs</summary>

```js
const path = require('path');
const webpackConfig = require('./webpack.config.cjs');

module.exports = {
  serverPort: process.env.SERVER_PORT,
  components: 'src/elements/**/*.vue',
  require: [
    path.join(__dirname, 'src/assets/fonts/fonts.scss'),
  ],
  theme: {
    fontFamily: {
      base: '"LL Circular", sans-serif',
    },
  },
  // Collapse sidebar navigation
  tocMode: 'collapse',
  getComponentPathLine(componentPath) {
    const name = path.basename(componentPath, '.vue');
    return `import { Vy${name} } from '@vidyard/construction-yard';`;
  },
  pagePerSection: true,
  sections: [
    {
      name: 'About',
      sectionDepth: 2,
      sections: [
        {
          name: 'Getting Started',
          content: './docs/getting-started.md',
        },
        {
          name: 'Contributing',
          content: './docs/contributing.md',
        },
        {
          name: 'Adding New Components',
          content: './docs/adding-new-components.md',
        },
        {
          name: 'Pull Requests',
          content: './docs/pull-requests.md',
        },
        {
          name: 'Release Process',
          content: './docs/release-process.md',
        },
      ],
      components: () => ['./docs/components/Statistics.vue'],
    },
    {
      name: 'Design',
      sectionDepth: 2,
      sections: [
        {
          name: 'Design Tokens',
          content: './docs/tokens.md',
        },
        {
          name: 'Typography',
          components: () => [
            './docs/components/tokens/FontSize.vue',
            './docs/components/tokens/Spacing.vue',
            './docs/components/tokens/Depth.vue',
          ],
        },
      ],
      components: () => [
        './docs/components/tokens/Color.vue',
        './docs/components/tokens/All.vue',
      ],
    },
    {
      name: 'Forms',
      sectionDepth: 2,
      sections: [
        {
          name: 'Input',
          components: () => [
            './src/elements/forms/Autocomplete.vue',
            './src/elements/forms/Checkbox.vue',
            './src/elements/forms/input/Input.vue',
            './src/elements/forms/input/InputV2.vue',
            './src/elements/forms/text-area/TextArea.vue',
            './src/elements/forms/InputNumber.vue',
          ],
        },
        {
          name: 'Radio',
          components: () => [
            './src/elements/forms/radio/Radio.vue',
            './src/elements/forms/radio/RadioGroup.vue',
            './src/elements/forms/radio/RadioButton.vue',
          ],
        },
      ],
      components: () => [
        './src/elements/forms/date-picker/DatePicker.vue',
        './src/elements/forms/DateTimePicker.vue',
        './src/elements/forms/Switch.vue',
        './src/elements/forms/slider/Slider.vue',
      ],
    },
    {
      name: 'General',
      sectionDepth: 2,
      sections: [
        {
          name: 'Buttons',
          components: () => [
            './src/elements/general/buttons/Button.vue',
            './src/elements/general/buttons/OverflowMenu.vue',
            './src/elements/general/buttons/Menu.vue',
            './src/elements/general/buttons/MenuRadio.vue',
            './src/elements/general/buttons/CustomDatePicker.vue',
            './src/elements/general/buttons/Link.vue',
          ],
        },
        {
          name: 'Feedback',
          components: () => [
            './src/elements/general/Alert.vue',
            './src/elements/general/Banner.vue',
            './src/elements/general/toast/ToastComponent.vue',
          ],
        },
        {
          name: 'Tags',
          components: () => [
            './src/elements/general/Tag.vue',
            './src/elements/general/TagBox.vue',
          ],
        },
        {
          name: 'Breadcrumb',
          components: () => [
            './src/elements/general/Breadcrumb.vue',
            './src/elements/general/BreadcrumbItem.vue',
          ],
        },
        {
          name: 'Tooltips',
          components: () => [
            './src/elements/general/Tooltip.vue',
            './src/mixins/Tooltip.vue',
          ],
        },
        {
          name: 'Thumbnails',
          components: () => [
            './src/elements/general/Thumbnails/PlaylistThumbnail.vue',
            './src/elements/general/Thumbnails/VideoThumbnail.vue',
            './src/elements/general/Thumbnails/Thumbnail.vue',
          ],
        },
      ],
      components: () => [
        './src/elements/general/AspectRatio.vue',
        './src/elements/general/Progress.vue',
        './src/elements/general/Spinner.vue',
        './src/elements/general/Truncate.vue',
        './src/elements/general/TruncateList.vue',
        './src/elements/general/Badge.vue',
        './src/elements/general/ColorPicker/ColorPicker.vue',
        './src/elements/general/Icon.vue',
        './src/elements/general/Status.vue',
      ],
    },
    {
      name: 'Layout',
      sectionDepth: 2,
      sections: [
        {
          name: 'Tabs',
          components: () => [
            './src/elements/layout/tabs/Tabs.vue',
            './src/elements/layout/tabs/Tab.vue',
          ],
        },
        {
          name: 'Cards',
          components: () => [
            './src/elements/layout/cards/Card.vue',
            './src/elements/layout/cards/CardButton.vue',
          ],
        },
      ],
      components: () => [
        './src/elements/layout/Collapse.vue',
        './src/elements/layout/Dialog.vue',
        './src/elements/layout/DialogContainer.vue',
        './src/elements/layout/drag-and-drop/DragAndDrop.vue',
        './src/elements/layout/Grid.vue',
        './src/elements/layout/Heading.vue',
        './src/elements/layout/NavBar.vue',
        './src/elements/layout/Paragraph.vue',
        './src/elements/layout/SidePanel.vue',
        './src/elements/layout/Table.vue',
        './src/elements/layout/Pagination.vue',
        './src/elements/layout/Popover.vue',
        './src/elements/layout/SortableTh.vue',
        './src/elements/layout/OverflowObserver.vue',
      ],
    },
  ],
  webpackConfig,
};
```

</details>

and our relevant package.json

<details>
<summary>package.json</summary>

```json
{
  "peerDependencies": {
    "@fortawesome/fontawesome-pro": "^5.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-brands-svg-icons": "^5.9.0",
    "@fortawesome/pro-light-svg-icons": "^5.9.0",
    "@fortawesome/pro-regular-svg-icons": "^5.9.0",
    "@fortawesome/pro-solid-svg-icons": "^5.9.0",
    "@fortawesome/vue-fontawesome": "^0.1.6",
    "lodash": "^4.17.5",
    "vue": "2.7.10"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "@babel/plugin-transform-runtime": "^7.11.5",
    "@babel/preset-env": "^7.11.5",
    "@fortawesome/fontawesome-pro": "^5.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-brands-svg-icons": "^5.9.0",
    "@fortawesome/pro-light-svg-icons": "^5.9.0",
    "@fortawesome/pro-regular-svg-icons": "^5.9.0",
    "@fortawesome/pro-solid-svg-icons": "^5.9.0",
    "@fortawesome/vue-fontawesome": "^0.1.8",
    "@vue/test-utils": "^1.1.0",
    "autoprefixer": "^9.7.6",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.3.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-dynamic-import-node": "^2.3.3",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^4.1.0",
    "codemirror": "^5.57.0",
    "compression-webpack-plugin": "^1.1.11",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "custom-event-polyfill": "^0.3.0",
    "eslint": "^7.9.0",
    "eslint-config-airbnb-base": "^14.2.0",
    "eslint-import-resolver-webpack": "^0.13.0",
    "eslint-plugin-compat": "^3.8.0",
    "eslint-plugin-es5": "^1.3.1",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-vue": "^6.2.2",
    "eslint-plugin-vuejs-accessibility": "^0.7.1",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy-middleware": "^0.18.0",
    "husky": "^0.14.3",
    "jest": "^26.4.2",
    "jest-serializer-vue": "^2.0.0",
    "lodash": "^4.17.5",
    "makeup-screenreader-trap": "^0.0.5",
    "mini-css-extract-plugin": "^0.11.2",
    "node-notifier": "^5.2.1",
    "npm-run-all": "^4.1.2",
    "onchange": "^4.0.0",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^2.0.0",
    "plop": "^2.2.1",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.1.3",
    "postcss-url": "^7.3.2",
    "prettier": "^1.12.0",
    "promise-polyfill": "^7.1.2",
    "rimraf": "^2.6.0",
    "sass": "^1.49.9",
    "sass-loader": "^10.2.0",
    "semver": "^5.5.0",
    "shelljs": "^0.8.1",
    "shifty": "^2.3.1",
    "style-loader": "^0.20.3",
    "sugar": "^2.0.4",
    "theo": "^7.0.1",
    "tinycolor2": "^1.4.1",
    "tooltip.js": "^1.2.0",
    "uglifyjs-webpack-plugin": "^1.2.4",
    "url-loader": "^1.0.1",
    "vue": "2.7.10",
    "vue-docgen-api": "^4.41.2",
    "vue-focus-lock": "^1.4.0",
    "vue-jest": "^4.0.0-rc.0",
    "vue-loader": "^15.10.0",
    "vue-lodash": "^2.0.0",
    "vue-meta": "^1.5.0",
    "vue-router": "^3.0.1",
    "vue-styleguidist": "^4.48.0",
    "vue-template-compiler": "2.7.10",
    "vuex": "^3.0.1",
    "webfontloader": "^1.6.28",
    "webpack": "^4.44.2",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^4.1.2",
    "webpack-merge-and-include-globally": "^1.0.1"
  },
  "engines": {
    "node": ">= 12.18.4",
    "yarn": ">= 0.19.1"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not Explorer > 0",
    "IE 11",
    "not ExplorerMobile > 0",
    "not BlackBerry > 0",
    "not OperaMini all",
    "not OperaMobile > 0"
  ],
  "dependencies": {
    "glob": "^7.1.3",
    "makeup-screenreader-trap": "^0.0.5",
    "shifty": "^2.3.1",
    "sugar": "^2.0.4",
    "tinycolor2": "^1.4.1",
    "tooltip.js": "^1.2.0"
  }
}
 ```
</details>

**Comment by elevatebart** [comment]
To answer your question, it never hurts to update the `vue-loader`.

If this does not work, would you mind terribly trying your hand at creating a reproduction repository?

This would very much accelerate diagnosis and fix.

Thank you in advance.

**Comment by JBarwick89** [comment]
`15.10.0` is the last version of `vue-loader` with Vue2 support, right?

**Comment by elevatebart** [comment]
My attempt at reproducing the issue: 
https://github.com/elevatebart/test-vsg-issue-1384

As is, the config you gave seems to work. I must be missing something.
Feel free to fork, clone, make it fail and link back your new failing repository here.

**Comment by elevatebart** [comment]
I suspect it has to do with something special in your webpack config. Sometimes, Loading es modules is not making css modules happy. Sometimes, there is a loader that makes babel cry.

I hope this helps.

**Comment by JBarwick89** [comment]
Thanks Bart


~~Was there something that changed recently related to the usage of `UglifyJsPlugin`. Looking through the releases that have occurred recently, there doesn't seem to be~~

~~But we have this in our config and the error we see does look like incorrect minified code. so wonder if this usage is what is causing our issues.~~

```
 dangerouslyUpdateWebpackConfig(config) {
    config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin');
    return config;
  },
```

I don't believe this is the issue

**Comment by JBarwick89** [comment]
It looks like the components that are rendering correctly are ones that do not have css classes or css imports in their docs.

**Comment by elevatebart** [comment]
Now we are making progress. 

Thank you @JBarwick89.

I am going to try this in the example.

**Comment by elevatebart** [comment]
I dded an import to the example and it still renders the styleguide.

It would be so much simpler for both of us if you added one of your failing components to my example repo, in a fork.
You can strip it of all proprietary code to avoid getting into trouble.

One failing component + docs should be enough.

Essentially, it's to create a test so that you are not facing the same issue in a month or two.

Bonus points, you might actually find a (temporary) way around the issue on your own.

**Comment by JBarwick89** [comment]
@elevatebart I have not been able to recreate in a fork yet.

I did find further that it is specifically the CSS in the markdown files that is causing our errors.
Moving the style blocks outside of the back ticks allows the style guide to render correctly.
does this sound like a css-loader issue?

**Comment by elevatebart** [comment]
It unfortunately does not sound like it. 
The style block in Single File Component style example is managed internally through a few lines of code:

https://github.com/vue-styleguidist/vue-styleguidist/blob/a47cbb9310251bb443be81b04e0767a6bfddf18d/packages/vue-styleguidist/src/client/rsg-components/Preview/PreviewAsync.js#L146-L148

Do you think it cloud be those lines that say `B is not a function`?

**Comment by elevatebart** [comment]
Do you have `@import` statements in those style blocks?

**Comment by JBarwick89** [comment]
we do have `@import` statements in some, but even those without that have the same error
