### ISSUE TITLE
Docs fpr methods won't show up

### ISSUE THREAD

**Issue by dasmikko** [vue-styleguidist/vue-styleguidist#1469]
**Current behavior**

I'm trying to write some documentation for public methods in my SFC that uses <script setup>.

**To reproduce**

Using the vite example inside the repo.

Example component:

<template>
  <div class="item">
    <i>
      <slot name="icon"></slot>
    </i>
    <div class="details">
      <h3>
        <slot name="heading"></slot>
      </h3>
      <slot></slot>
    </div>
  </div>
</template>

```
<script setup>

const props = defineProps({
  /**
   * A simple test prop
   */
  testProp: {
    type: String,
    default: 'lol'
  }
})

/**
 * Test method exposed
 * 
 * @returns {String} Returns a simple string
 */
const test = () => {
  return 'test'
}

defineExpose({
  /**
 * Test method exposed
 * 
 * @returns {String} Returns a simple string
 */
  test
})
</script>

```

Neither of the comments for the method or inside the `defineExpose` show up in vitepress.

**Expected behavior**

I expected docs for methods to show up in vitepress.

**Comment by dasmikko** [comment]
Hi, thanks for the quick fix for this, it seems to throw an error when running,

```
[username@hostname project]$ npm run styleguide

> project@0.11.37 styleguide
> concurrently "vue-docgen --watch" "vitepress dev docs"

[1] vitepress v1.0.0-alpha.40
[0] /home/username/repos/project/node_modules/vue-docgen-cli/lib/multiMd.js:97
[0]                 throw new Error(`Error compiling file ${file}: ${err.message}`);
[0]                       ^
[0] 
[0] Error: Error compiling file /home/username/repos/project/docs/components/button/Button.md: Error parsing file /home/username/repos/project/lib/components/button/Button.vue:templates.expose is not a function
[0]     at /home/username/repos/project/node_modules/vue-docgen-cli/lib/multiMd.js:97:23
[0]     at Generator.throw (<anonymous>)
[0]     at rejected (/home/username/repos/project/node_modules/vue-docgen-cli/lib/multiMd.js:29:65)
[0] 
[0] Node.js v18.12.1
[0] vue-docgen --watch exited with code 1
[1] 
[1]   ➜  Local:   http://localhost:5173/docgen-vite/
[1]   ➜  Network: use --host to expose
```
