### ISSUE TITLE
Error when documenting defineExpose

### ISSUE THREAD

**Issue by dasmikko** [vue-styleguidist/vue-styleguidist#1472]
The new fix (#1469) for documenting defineExpose does not seem to work as intended.

It gives me the following error when trying to run styleguidist:

```
[username@hostname project]$ npm run styleguide

> project@0.11.37 styleguide
> concurrently "vue-docgen --watch" "vitepress dev docs"

[1] vitepress v1.0.0-alpha.40
[0] /home/username/repos/project/node_modules/vue-docgen-cli/lib/multiMd.js:97
[0]                 throw new Error(`Error compiling file ${file}: ${err.message}`);
[0]                       ^
[0] 
[0] Error: Error compiling file /home/username/repos/project/docs/components/button/Button.md: Error parsing file /home/username/repos/project/lib/components/button/Button.vue:templates.expose is not a function
[0]     at /home/username/repos/project/node_modules/vue-docgen-cli/lib/multiMd.js:97:23
[0]     at Generator.throw (<anonymous>)
[0]     at rejected (/home/username/repos/project/node_modules/vue-docgen-cli/lib/multiMd.js:29:65)
[0] 
[0] Node.js v18.12.1
[0] vue-docgen --watch exited with code 1
[1] 
[1]   ➜  Local:   http://localhost:5173/docgen-vite/
[1]   ➜  Network: use --host to expose
```

**Comment by elevatebart** [comment]
Uh Ooooooh, Sorry I really should have tested this.

**Comment by elevatebart** [comment]
Will be fixed in the next hour

**Comment by dasmikko** [comment]
No worries, we all make mistakes! 👍

**Comment by dasmikko** [comment]
Yay, new versions works, thanks for the quick response!
