### ISSUE TITLE
[plugin:storybook:vue-docgen-plugin] did not recognize object of type "TSInstantiationExpression"

### ISSUE THREAD

**Issue by vmerz** [vue-styleguidist/vue-styleguidist#1530]
Discovered this bug while using [storybook](https://storybook.js.org) which uses vue-docgen-api.

**Current behavior**

Crash with error

```
Plugin: storybook:vue-docgen-plugin
  File: /myProject/src/components/Test.vue
      at Object.getFieldNames (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/types.js:664:19)
      at visitChildren (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:184:36)
      at Visitor2.PVp.visitWithoutReset (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:166:20)
      at visitChildren (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:203:25)
      at Visitor2.PVp.visitWithoutReset (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:166:20)
      at NodePath2.each (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path.js:87:26)
      at visitChildren (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:178:18)
      at Visitor2.PVp.visitWithoutReset (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:166:20)
      at visitChildren (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:203:25)
      at Visitor2.PVp.visitWithoutReset (/myProject/node_modules/vue-docgen-api/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:166:20)
```

**To reproduce**

A typed map does not work:

```vue
<script setup
        lang="ts">

const props = defineProps({
  foo: {
    type: Map<number, number>,
  },
});
</script>

<template>
  {{ props.foo }}
</template>
```

If we leave out the types, it works

```vue
<script setup
        lang="ts">

const props = defineProps({
  foo: {
    type: Map,
  },
});
</script>

<template>
  {{ props.foo }}
</template>
```

**Expected behavior**

no crash ;)

**Comment by elevatebart** [comment]
I am surprised it works...

I would have written it this way instead:

```vue
<script setup lang="ts">

const props = defineProps<{
  foo: Map<number, number>,
}>();
</script>

<template>
  {{ props.foo }}
</template>
```

It should never crash anyway.
