### ISSUE TITLE
vue-docgen-plugin: Did not recognize object of type "TSSatisfiesExpression"

### ISSUE THREAD

**Issue by JoJk0** [vue-styleguidist/vue-styleguidist#1531]
**Current behavior**

It looks like the plugin doesn't know about the new TypeScript 4.9 [`satisfies` operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator)

A bug discovered while using Storybook v7 with Vue and Vite.

```sh
[vite] Internal server error: did not recognize object of type "TSSatisfiesExpression"
  Plugin: storybook:vue-docgen-plugin
  File: .../src/components/AppEnvBadge.vue
      at Object.getFieldNames (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\types.js:586:13)
      at visitChildren (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:153:30)
      at Visitor2.PVp.visitWithoutReset (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:138:14)
      at visitChildren (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:167:17)
      at Visitor2.PVp.visitWithoutReset (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:138:14)
      at NodePath2.each (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path.js:71:18)      
      at visitChildren (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:150:12)
      at Visitor2.PVp.visitWithoutReset (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:138:14)
      at visitChildren (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:167:17)
      at Visitor2.PVp.visitWithoutReset (...\node_modules\.pnpm\ast-types@0.15.2\node_modules\ast-types\lib\path-visitor.js:138:14)
```

**To reproduce**

Use `satisfies` TypeScript expression inside `.vue` component that is imported by the Storybook

```vue
<template>
	<button @click.prevent="onClick">
		test
	</button>
</template>

<script lang="ts">

interface Blob {
  tot: string
  foo: string
}

const bob = {
  tot: 'tot',
  foo: 'foo'
} satisfies Blob

export default {
	name: 'DsButton',
	props: {}
}
</script>
```

**Expected behavior**

No error to display

**Comment by elevatebart** [comment]
Thank you @JoJk0 

Would you have time to share a component code that triggers this issue?

This would help me fix it in a timely manner.

**Comment by elevatebart** [comment]
Connected to https://github.com/benjamn/ast-types/issues/935
