### ISSUE TITLE
Trouble with Vue 2 + Typescript + Nuxt

### ISSUE THREAD

**Issue by Tobjoern** [vue-styleguidist/vue-styleguidist#1607]
I'm trying to add vue-styleguidist to an existing project, which uses Vue 2, with nuxt and Typescript.
I already looked through the existing examples, and tried to get it to work with the 'nuxtjs' and 'vuecli3-class-pug-ts' examples, however both didn't work.

When trying to run the 'vuecli3-class-pug-ts' example with `npm run styleguide` I get the following error:
```
❯ npm run styleguide

> vuecli3-class-pug-ts@4.0.0 styleguide
> vue-cli-service styleguidist

/Users/me/coding/vue-styleguidist/examples/vuecli3-class-pug-ts/node_modules/@vue/cli-service/lib
Using webpack from /Users/me/coding/vue-styleguidist/examples/vuecli3-class-pug-ts/node_modules/@vue/cli-service/node_modules/webpack/lib/index.js
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
/Users/me/coding/vue-styleguidist/examples/vuecli3-class-pug-ts/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:309
                                        throw this.error(
                                        ^

Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[4].resource.test: (resource) => {
        currentResource = resource
        return true
      })
    at RuleSetCompiler.error (/Users/me/coding/vue-styleguidist/examples/vuecli3-class-pug-ts/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:373:10)
    at RuleSetCompiler.compileCondition (/Users/me/coding/vue-styleguidist/examples/vuecli3-class-pug-ts/node_modules/@vue/cli-service/node_modules/webpack/lib/rules/RuleSetCompiler.js:309:17)
```

I created a small reproduction with instructions here: https://github.com/Tobjoern/vue-stylguidist-ts-nuxt

When running the reproduction, I get the following error(s):
Module parse failed: Unexpected character '@' (29:0)
File was processed with these loaders:
```
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import { ReactivityUtils } from "~/utils/ReactivityUtils";
| 
> @Component({})
| export default class MonthlyYearlyInput extends mixins(TypedStoreMixin) {
|   @Prop({ required: true })
```

I assume, it's a webpack (typescript) issue I'm facing, as the loader doesn't seem to know how to load the project correctly, which is strange, since I get the actual webpack config via nuxt's 'getWebpackConfig' command, and the project itself works.
It's also important to note, that I don't necessarily need to render the actual components in the documentation, I'm with not having a preview, but just displaying the documentation itself.

I already spent 7+ hours getting it to work, I'd highly appreciate your help!

**Comment by Tobjoern** [comment]
Hey @elevatebart,
do you have some tips you can give me?
I'm under a bit of time pressure, since I have to give a presentation about an important project in 10 days.

**Comment by elevatebart** [comment]
I can't seem to find out why nuts web pack config would not have a loader for ts files.
I wonder how they support TS. Anyway, that is indeed what is missing. 

Until I find out why, you could use a ts loader yourself and add it to the rules.
