### ISSUE TITLE
Bug in prop type detection of vue-docgen-api 4.79.1

### ISSUE THREAD

**Issue by sawmurai** [vue-styleguidist/vue-styleguidist#1678]
**Current behavior**

```
/Users/.../master/node_modules/vue-docgen-api/dist/script-setup-handlers/utils/tsUtils.js:108
                                return prop.key.type === 'Identifier' &&
                                                ^

TypeError: Cannot read properties of undefined (reading 'type')
    at /Users/.../master/node_modules/vue-docgen-api/dist/script-setup-handlers/utils/tsUtils.js:108:49
    at Array.find (<anonymous>)
    at /Users.../master/node_modules/vue-docgen-api/dist/script-setup-handlers/utils/tsUtils.js:105:56
    at Array.forEach (<anonymous>)
    at /Users/.../master/node_modules/vue-docgen-api/dist/script-setup-handlers/utils/tsUtils.js:104:125
    at Array.forEach (<anonymous>)
    at Context.visitTSInterfaceDeclaration (/Users/.../master/node_modules/vue-docgen-api/dist/script-setup-handlers/utils/tsUtils.js:99:38)
    at Context.invokeVisitorMethod (/Users/.../master/node_modules/ast-types/lib/path-visitor.js:283:51)
    at PVp.visitWithoutReset (/Users/.../master/node_modules/ast-types/lib/path-visitor.js:158:32)
    at visitChildren (/Users/.../master/node_modules/ast-types/lib/path-visitor.js:204:25)

Node.js v20.12.2

```

**To reproduce**

I cannot upload the repo unfortunately. But I have some debugging output:

```
Node {
  type: 'Identifier',
  start: 805,
  end: 823,
  loc: SourceLocation {
    start: Position { line: 33, column: 2, index: 805, token: 85 },
    end: Position { line: 33, column: 20, index: 823, token: 86 },
    filename: undefined,
    identifierName: 'maxDisplayedAlerts',
    lines: Lines {
      infos: [Array],
      mappings: [],
      cachedSourceMap: null,
      cachedTabWidth: undefined,
      length: 70,
      name: null
    },
    tokens: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Object], [Token],  [Token],  [Token],  [Token],
      [Object], [Token],  [Token],  [Token],  [Token],  [Token],
      [Object], [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],  [Token],  [Token],
      [Token],  [Token],  [Token],  [Token],
      ... 266 more items
    ],
    indent: 2
  },
  name: 'maxDisplayedAlerts',
  optional: false,
  typeAnnotation: null
}
```

This is the output of `console.log(prop)`. You see it has no `key` attribute. 

**Expected behavior**

What vue-docgen-api 4.78.0 did :)

**Comment by elevatebart** [comment]
could it be that you are using something like this?

```js
const firstProp = {
   maxDisplayedAlerts: Number
}

defineProps({
  maxDisplayedAlerts
})
```

**Comment by sawmurai** [comment]
Thank you!
