### ISSUE TITLE
Support webpack mode

### ISSUE THREAD

**Issue by OmgImAlexis** [vue-styleguidist/vue-styleguidist#173]
I'm trying to use this with one of my projects and I keep getting this error as I don't believe you support the new webpack `mode`. If it helps [here](https://github.com/pymedusa/Medusa/tree/develop/themes-default/slim) is the directory for the project. I also tried just passing `--mode development` but that didn't work either.

<details>
  <summary><code>webpack.conf.js</code></summary>

```js
const path = require('path');
const { ProvidePlugin } = require('webpack');
const VueLoaderPlugin = require('vue-loader/lib/plugin');
const FileManagerPlugin = require('filemanager-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const pkg = require('./package.json');

const { config } = pkg;
const { cssThemes } = config;

const webpackConfig = mode => ({
    entry: {
        // Exports all window. objects for mako files
        index: path.resolve(__dirname, 'src/index.js'),
        // Main Vue app
        app: path.resolve(__dirname, 'src/app.js')
    },
    output: {
        filename: 'js/[name].js',
        path: path.resolve(__dirname, 'dist')
    },
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: {
            vue$: 'vue/dist/vue.esm.js'
        }
    },
    performance: {
        hints: false
    },
    stats: {
        // When `false`, hides extra information about assets collected by children (e.g. plugins)
        children: false
    },
    optimization: {
        runtimeChunk: {
            name: 'vendors'
        },
        splitChunks: {
            chunks: 'all',
            name: 'vendors',
            cacheGroups: {
                styles: {
                    test: /\.css$/,
                    priority: 10
                },
                // These are the default cacheGroups!
                vendors: {
                    test: /[\\/]node_modules[\\/]/,
                    priority: -10
                },
                default: {
                    minChunks: 2,
                    priority: -20,
                    reuseExistingChunk: true
                }
            }
        }
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                use: [{
                    loader: 'vue-loader',
                    options: {
                        // This is a workaround because vue-loader can't get the webpack mode
                        productionMode: mode === 'production'
                    }
                }]
            },
            {
                test: /\.js$/,
                loader: 'babel-loader'
            },
            {
                // This rule may get either actual `.css` files or the style blocks from `.vue` files.
                // Here we delegate each request to use the appropriate loaders.
                test: /\.css$/,
                oneOf: [
                    {
                        // Handle style blocks in `.vue` files
                        // Based on this query: https://github.com/vuejs/vue-loader/blob/v15.2.7/lib/codegen/styleInjection.js#L27
                        resourceQuery: /^\?vue&type=style/,
                        use: [
                            'vue-style-loader',
                            'css-loader'
                        ]
                    },
                    {
                        // Handle regular `.css` files
                        use: [
                            {
                                loader: MiniCssExtractPlugin.loader,
                                options: {
                                    // Fixes loading fonts from the fonts folder
                                    publicPath: '../'
                                }
                            },
                            'css-loader'
                        ]
                    }
                ]
            },
            {
                test: /\.(woff2?|ttf|eot|svg)$/,
                use: [{
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]',
                        outputPath: 'fonts'
                    }
                }]
            }
        ]
    },
    plugins: [
        // This fixes Bootstrap being unable to use jQuery
        new ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery'
        }),
        new VueLoaderPlugin(),
        new MiniCssExtractPlugin({
            filename: 'css/[name].css'
        }),
        new FileManagerPlugin({
            onEnd: {
                copy: Object.values(cssThemes).reduce((operations, theme) => {
                    // Queue operations for each theme
                    operations.push({
                        source: './dist/js/**',
                        destination: path.join(theme.dest, 'assets', 'js')
                    });
                    operations.push({
                        source: './dist/css/**',
                        destination: path.join(theme.dest, 'assets', 'css')
                    });
                    operations.push({
                        source: './dist/fonts/**',
                        destination: path.join(theme.dest, 'assets', 'fonts')
                    });
                    return operations;
                }, [])
            }
        })
    ]
});

module.exports = (_env, argv) => webpackConfig(argv.mode);
```

</details>

&nbsp;

```shell
➜  slim git:(develop) ✗ NODE_ENV=development yarn styleguide
yarn run v1.7.0
warning package.json: No license field
$ vue-styleguidist server
Loading webpack config from:
/Users/xo/code/Medusa/themes-default/slim/webpack.config.js

TypeError: Cannot read property 'mode' of undefined
TypeError: Cannot read property 'mode' of undefined
    at module.exports (/Users/xo/code/Medusa/themes-default/slim/webpack.config.js:150:53)
    at mergeWebpackConfig (/Users/xo/code/Medusa/themes-default/slim/node_modules/vue-styleguidist/scripts/utils/mergeWebpackConfig.js:45:52)
    at module.exports (/Users/xo/code/Medusa/themes-default/slim/node_modules/vue-styleguidist/scripts/make-webpack-config.js:64:20)
    at createServer (/Users/xo/code/Medusa/themes-default/slim/node_modules/vue-styleguidist/scripts/create-server.js:7:24)
    at server (/Users/xo/code/Medusa/themes-default/slim/node_modules/vue-styleguidist/scripts/server.js:5:21)
    at commandServer (/Users/xo/code/Medusa/themes-default/slim/node_modules/vue-styleguidist/bin/styleguidist.js:121:19)
    at Object.<anonymous> (/Users/xo/code/Medusa/themes-default/slim/node_modules/vue-styleguidist/bin/styleguidist.js:70:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by elevatebart** [comment]
Hello @OmgImAlexis, glad you are enjoying styleguidist.
I was looking at your use case and saw something unusual.

The last line of your webpack.config 
```
module.exports = (_env, argv) => webpackConfig(argv.mode);
```
only makes sense when using webpack as a command line tool. 

It would probably be more simple to directly export a function.
Or in your case, it would probably be more efficient to simply ommit the mode entirely as it is completely handled by webpack and vue-loader.

Tell me if it works ;)

**Comment by elevatebart** [comment]
You can find more info [here](https://webpack.js.org/configuration/configuration-types/#exporting-a-function) about how to export a function for webpack whiI think is what you are trying to do.

**Comment by elevatebart** [comment]
Hey @OmgImAlexis did you try ?
Can I close this issue ?

**Comment by OmgImAlexis** [comment]
Oh shoot, sorry I lost the notification. I'll try that out soon.
