### ISSUE TITLE
Examples not working when following documentation 

### ISSUE THREAD

**Issue by tamm** [vue-styleguidist/vue-styleguidist#265]
I went to this example and ran the instructions (modified for vuetify example, but same thing happens with basic)
https://github.com/vue-styleguidist/vue-styleguidist/blob/master/examples/vuetify/Readme.md

I get this error:
```
tamm$ npm run styleguide

> vue-styleguidist-example-vuetify@1.8.11 styleguide /Users/tamm/projects/vue-styleguidist/examples/vuetify
> vue-styleguidist server

TypeError: Cannot read property 'filter' of undefined
TypeError: Cannot read property 'filter' of undefined
    at webpackConfig.module.rules.rules.map.rule (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/scripts/utils/mergeWebpackConfigVueCLI.js:34:20)
    at Array.map (<anonymous>)
    at mergeWebpackConfigVueCLI (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/scripts/utils/mergeWebpackConfigVueCLI.js:30:38)
    at module.exports (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/scripts/make-webpack-config.js:70:20)
    at createServer (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/scripts/create-server.js:7:24)
    at server (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/scripts/server.js:5:21)
    at commandServer (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/bin/styleguidist.js:123:19)
    at Object.<anonymous> (/Users/tamm/projects/vue-styleguidist/examples/vuetify/node_modules/vue-styleguidist/bin/styleguidist.js:72:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-styleguidist-example-vuetify@1.8.11 styleguide: `vue-styleguidist server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-styleguidist-example-vuetify@1.8.11 styleguide script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

By instead doing the following the examples work:
```
git clone https://github.com/vue-styleguidist/vue-styleguidist.git
cd vue-styleguidist
npm install
npm run compile
npm run start vuetify
```

I don't know what the issue is with the example, but please update the documentation if it's not a problem so this doesn't end up confusing others. :)

**Comment by elevatebart** [comment]
hey @tamm,

I took me a minute but I manged to make it work.

I just created PR #266

**Comment by tamm** [comment]
Awesome, that was so fast!
I've pulled that branch and the examples work as expected for me now.

**Comment by elevatebart** [comment]
Great !!
