### ISSUE TITLE
Cannot find module 'fork-ts-checker-webpack-plugin', Breaking error in v1.0.4 

### ISSUE THREAD

**Issue by JessicaSachs** [vue-styleguidist/vue-styleguidist#270]
I'm getting an exception when I'm trying to run `npm run serve` in a super simple project. styleguidist v 0.2.1 works fine

> bird@0.1.0 serve /Users/jessicasachs/projects/bird
> vue-cli-service serve

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'fork-ts-checker-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jessicasachs/projects/bird/node_modules/react-dev-utils/WebpackDevServerUtils.js:21:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jessicasachs/projects/bird/node_modules/vue-styleguidist/scripts/binutils.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bird@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bird@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jessicasachs/.npm/_logs/2019-02-10T23_20_05_883Z-debug.log

**Comment by elevatebart** [comment]
Hey jess, did you use the vue-cli plugin[https://github.com/vue-styleguidist/vue-cli-plugin-styleguidist] ?

**Comment by elevatebart** [comment]
I see that you do. I missed the version number.

Could you please share the `devDependencies` portion of your `package.json` ?

**Comment by elevatebart** [comment]
Outside of this scope, does `npm run styleguide` work ?

**Comment by elevatebart** [comment]
You just might have to update most or the cli to match the version in the plugin.

**Comment by elevatebart** [comment]
Here is the explaination: 
In react-dev-utils@7.0.2, react-dev-utils became highly dependent on create-react-app. 
Facebook, more specifically https://github.com/deftomat added a line in this file 
https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/WebpackDevServerUtils.js without adding the proper dependency to their package.json

I will carve an issue/PR combo tomorrow ;)
Until the noone should use react-dev-utils@7.0.2
