### ISSUE TITLE
Cannot use modules that reference window inside of "context" option

### ISSUE THREAD

**Issue by JessicaSachs** [vue-styleguidist/vue-styleguidist#286]
So you can require helpers and fixtures inside of your `<docs>` that depend on window, and that works fine... but then when you try to require those fixtures globally using the context option, styleguidist fails to compile. :-(

```
> Tags@1.0.0 styleguide /Users/jessicasachs/projects/tags
> vue-cli-service styleguidist

ReferenceError: window is not defined
    // vv this guy depends on window, isn't usually an issue inside of a <docs> block!
    at Object.<anonymous> (/Users/jessicasachs/projects/tags/node_modules/im-toolkit/_lib/global_storage/toolkitNamespace.js:3:1) 
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jessicasachs/projects/tags/node_modules/im-toolkit/_lib/global_storage/PersistentArray.js:1:86)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by elevatebart** [comment]
This is unfortunate indeed. 
We are using react-styleguidist examples-loader directly.

Each context member is loaded inside the loader (in node) at 
https://github.com/styleguidist/react-styleguidist/blob/master/src/loaders/examples-loader.js#L69
At this point window is not defined.
You could wrap your library to make sure it is defined. 
I am not sure it would help.

Are you trying to include something globally?
For this, the option [renderRootJsx](https://vue-styleguidist.github.io/Configuration.html#renderrootjsx) would be very useful. Have look at the vuex example in the guide.

tell em if it helps

**Comment by JessicaSachs** [comment]
It's really ugly but it's working... thank you for the tip!

Let me know if you have a way to make this less gnarly.

```javascript
export default previewComponent => {
    const oldData = typeof previewComponent.data === 'function' ? previewComponent.data() : {};
    const globals = { MockData: require('./someMockData.js') };

    // Reassign the data function on the preview component
    // to add the globals to the Preview Component's context...
    // Make sure that the "globals" you're adding are namespaced appropriately
    /// so you don't collide with property names, etc..
    previewComponent.data = () => Object.assign(globals, oldData);

    return {
        render(h) {
            return h(
                'div',
                {},
                [h(previewComponent)]
            )
        }
    }
}
```

**Comment by elevatebart** [comment]
So the plugin you are loading gets the data from the window object right ?
And makes it vailable to components. Seems neat.
