### ISSUE TITLE
Can't install vue-styleguidist

### ISSUE THREAD

**Issue by victory-v** [vue-styleguidist/vue-styleguidist#633]
**Current behavior**
When I try to install via yarn, I get an error:
```
Error: Couldn't find package "is-obj" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:47179:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Error: Couldn't find package "dir-glob" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:47179:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Error: Couldn't find package "aggregate-error" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:47179:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Error: Couldn't find package "common-sequence" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:47179:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Error: Couldn't find package "cliui" on the "npm" registry.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at NpmResolver.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:47179:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:109:13
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
UPD: actually I get errors about different packages every time

Installing vue-cli-plugin-styleguidist the same.

**To reproduce**

`$ yarn add vue-styleguidist`

**Expected behavior**

vue-styleguidist is installed correctly

**Comment by elevatebart** [comment]
Hello @victory-v 

Have you tried running `yarn cache clean`? it might be that your local repo is corrupted.
Are you allowed to share your package.json? This would probably be very useful as well if the first solution does not work.

Then in the root folder of your project you should get a `yarn-error.log` file. If you can, please share it too.

Thank you for your interest in the lib. We will have you designing in no time ;)

**Comment by victory-v** [comment]
It seems that something was wrong on my side, I didn't really get what happened. `yarn cache clean` didn't work and I had to create a new project in my IDE because I didn't had any time left to struggle with this errors :)
But I got another error when I tried to run styleguide, so I'll create another issue if you don't mind :)
