### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by pocka** [vue-styleguidist/vue-styleguidist#749]
**Current behavior**

https://github.com/storybookjs/storybook/issues/9821

`vue-docgen-api` throws a TypeError when there is a comment line before `<slot/>` tag and it has no `@slot` tag.

```
TypeError: Cannot read property 'content' of undefined
    at /sandbox/node_modules/vue-docgen-api/dist/template-handlers/slotHandler.js:64:25
    at Array.forEach (<anonymous>)
    at slotHandler (/sandbox/node_modules/vue-docgen-api/dist/template-handlers/slotHandler.js:59:18)
    at /sandbox/node_modules/vue-docgen-api/dist/parse-template.js:59:13
    at Array.forEach (<anonymous>)
    at traverse (/sandbox/node_modules/vue-docgen-api/dist/parse-template.js:58:18)
    at traverseAstChildren (/sandbox/node_modules/vue-docgen-api/dist/parse-template.js:43:21)
    at traverse (/sandbox/node_modules/vue-docgen-api/dist/parse-template.js:69:13)
    at Object.parseTemplate [as default] (/sandbox/node_modules/vue-docgen-api/dist/parse-template.js:28:13)
    at Object.<anonymous> (/sandbox/node_modules/vue-docgen-api/dist/parseSFC.js:95:45)
```

**To reproduce**

- https://github.com/mattgreenfield/storybook-vue-sandbox (from an original issue)
- https://codesandbox.io/s/vue-docgen-api-html-comment-4zgc3 (CodeSandbox using `vue-docgen-api` directly)

**Expected behavior**

The tool just ignores the comment line.

**Comment by pocka** [comment]
Thank you for the quick fix!
