### ISSUE TITLE
Error: No matching use for vue-loader is found

### ISSUE THREAD

**Issue by rachel-flux** [vue-styleguidist/vue-styleguidist#883]
Hello,

I am trying to get vue-styleguidist configured in my existing app.  I have attempted to install via Vue CLI 3 or `vue-styleguidist` directly, and with our without `webpackConfig` defined in styleguide.config.js, but no combinations are working for me.

Do you see anything wrong with my setup?

**_package.json_**

```
{
  "name": "fm-client",
  "version": "0.1.0",
  "private": true,
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,vue}": [
      "vue-cli-service lint",
      "git add"
    ]
  },
  "scripts": {
    "serve": "npx vue-cli-service serve",
    "devstart": "npx vue-cli-service serve",
    "deve2e": "npx cypress open",
    "build": "npx vue-cli-service build",
    "servebuild": "npx serve -p 8080 -s dist",
    "lint": "npx vue-cli-service lint",
    "test:unit": "npx vue-cli-service test:unit",
    "test:e2e": "npx cypress run",
    "styleguide": "vue-cli-service styleguidist",
    "styleguide:build": "vue-cli-service styleguidist:build"
  },
  "dependencies": {
    "@amcharts/amcharts4": "^4.9.22",
    "@ibm/plex": "^4.0.2",
    "@sentry/browser": "^5.15.5",
    "@sentry/integrations": "^5.15.5",
    "auth0-js": "^9.13.2",
    "auth0-lock": "^11.24.0",
    "axios": "^0.19.2",
    "core-js": "^3.6.5",
    "jsonwebtoken": "^8.5.1",
    "lodash-es": "^4.17.15",
    "material-design-icons-iconfont": "^5.0.1",
    "moment": "^2.25.3",
    "moment-timezone": "^0.5.28",
    "retry-axios": "^2.1.3",
    "sharp": "^0.25.2",
    "short-uuid": "^3.1.1",
    "sortablejs": "^1.10.2",
    "survey-vue": "^1.7.6",
    "surveyjs-widgets": "^1.7.6",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6",
    "vue-wait": "^1.4.8",
    "vue2-editor": "^2.10.2",
    "vuedraggable": "^2.23.2",
    "vuejs-logger": "^1.5.4",
    "vuetify": "^2.2.28",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-optional-chaining": "^7.9.0",
    "@cypress/code-coverage": "^3.7.2",
    "@vue/cli-plugin-babel": "^4.3.1",
    "@vue/cli-plugin-eslint": "^4.3.1",
    "@vue/cli-service": "^4.3.1",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "@vue/test-utils": "^1.0.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.0.1",
    "css-loader": "^3.5.3",
    "cypress": "^4.5.0",
    "cypress-failed-log": "^2.7.0",
    "deepmerge": "^4.2.2",
    "eslint": "^7.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^6.2.2",
    "eslint-plugin-vuetify": "^1.0.0-beta.6",
    "fibers": "^5.0.0",
    "istanbul-lib-coverage": "^3.0.0",
    "jimp": "^0.10.3",
    "lint-staged": "^10.2.2",
    "lodash": "^4.17.15",
    "nyc": "^15.0.1",
    "replace-in-file": "^6.0.0",
    "responsive-loader": "^1.2.0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "serve": "^11.3.0",
    "style-loader": "^1.2.1",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-styleguidist": "^4.23.3",
    "vue-cli-plugin-vuetify": "^2.0.5",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.4.3",
    "webpack-bundle-analyzer": "^3.7.0"
  }
}
```

**_vue.config.js_**

```
const replace = require('replace-in-file');
// eslint-disable-next-line import/no-extraneous-dependencies
const ResponsiveLoader = require('responsive-loader/sharp');
// eslint-disable-next-line import/no-extraneous-dependencies
const path = require('path');

module.exports = {
  configureWebpack: {
    // See https://github.com/webpack/docs/wiki/build-performance#sourcemaps
    // And devtool must be `eval` for istanbul coverage to work on .vue files
    // https://github.com/istanbuljs/nyc/issues/718#issuecomment-569346546
    devtool: process.env.NODE_ENV === 'production' ? 'source-map' : 'eval',
  },
  chainWebpack: (config) => {
    // When using lerna and simlinks,
    // mode some modules that should be ignored are not
    // we add them here to avoid errors
    const vueBrowserCompilerPath = path.resolve(
      path.dirname(require.resolve('vue-inbrowser-compiler')),
      '../',
    );

    const eslintRule = config.module.rule('eslint');
    if (eslintRule) {
      const vsgPath = path.resolve(path.dirname(require.resolve('vue-styleguidist')), '../');
      const docgenPath = path.resolve(path.dirname(require.resolve('vue-docgen-api')), '../');

      eslintRule.exclude.add(vsgPath);
      eslintRule.exclude.add(docgenPath);
      eslintRule.exclude.add(vueBrowserCompilerPath);
    }

    const jsRule = config.module.rule('js');
    if (jsRule) {
      jsRule.exclude.add(vueBrowserCompilerPath);
    }

    if (process.env.BABEL_ENV === 'test') {
      // https://github.com/istanbuljs/nyc/issues/718#issuecomment-569346546
      replace.sync({
        files: 'node_modules/istanbul-lib-source-maps/lib/get-mapping.js',
        from: 'source: pathutils.relativeTo(start.source, origFile),',
        to: 'source: origFile,',
      });
    }

    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap((options) => ({
        ...options,
        transformAssetUrls: {
          video: ['src', 'poster'],
          source: 'src',
          img: 'src',
          image: 'xlink:href',
          'v-img': ['src', 'srcset', 'lazy-src'],
          'v-card': 'src',
          'v-card-media': 'src',
          'v-responsive': 'src',
        },
      }));

    config.module
      .rule('gifs')
      .test(/\.(gif)$/i)
      .use('file-loader')
      .loader('file-loader');

    config.module.rule('images').uses.clear();

    config.module
      .rule('responsive-images')
      .test(/\.(jpe?g|png)$/i)
      .use('responsive-loader')
      .loader('responsive-loader')
      .tap((options) => ({
        ...options,
        adapter: ResponsiveLoader,
        sizes: [250, 600, 1200, 3000],
        placeholder: true,
        placeholderSize: 50,
        disable: process.env.NODE_ENV !== 'production',
      }));
  },
  css: {
    loaderOptions: {
      scss: {
        prependData: '@import "@/scss/colors.scss";',
      },
    },
  },
  transpileDependencies: [
    'regexpu-core',
    'strip-ansi',
    'ansi-regex',
    'ansi-styles',
    'react-dev-utils',
    'chalk',
    'unicode-match-property-ecmascript',
    'unicode-match-property-value-ecmascript',
    'acorn-jsx',
    'vuetify',
    'camelcase',
  ],
};
```

**_styleguide.config.js_**

```
module.exports = {
  title: 'Default Style Guide',
  components: 'src/components/testing/[A-Z]*.vue',
  defaultExample: false,
  ribbon: {
    text: 'Back to examples',
    url: '/',
  },
  sections: [
    {
      name: 'First Section',
      components: 'src/components/testing/[A-Z]*.vue',
    },
  ],
  // eslint-disable-next-line global-require
  webpackConfig: require('./node_modules/@vue/cli-service/webpack.config.js'),
  exampleMode: 'expand',
};

```

If I run with the config above, it results in the following error.

```
> Executing task in folder fm-client: npm run styleguide <

> vue-cli-service styleguidist

 ERROR  Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/Users/rachel/dev/local/fm-client/node_modules/vue-loader/lib/plugin-webpack4.js:59:13)
    at webpack (/Users/rachel/dev/local/fm-client/node_modules/webpack/lib/webpack.js:51:13)
    at createServer (/Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/scripts/create-server.js:45:42)
    at server (/Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/scripts/server.js:14:49)
    at Object.commandServer (/Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/scripts/binutils.js:130:41)
    at Object.server (/Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/scripts/index.js:76:25)
    at /Users/rachel/dev/local/fm-client/node_modules/vue-cli-plugin-styleguidist/index.js:47:64
    at Service.run (/Users/rachel/dev/local/fm-client/node_modules/@vue/cli-service/lib/Service.js:245:12)
    at Object.<anonymous> (/Users/rachel/dev/local/fm-client/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fm-client@0.1.0 styleguide: `vue-cli-service styleguidist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fm-client@0.1.0 styleguide script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rachel/.npm/_logs/2020-05-28T02_59_33_299Z-debug.log
The terminal process terminated with exit code: 1
```

I read [here](https://github.com/vue-styleguidist/vue-styleguidist/issues/525) that with Vue CLI 3 I shouldn't need to include `webpackConfig` in styleguide.config.js, but when I remove `webpackConfig` it fails to compile:

```
> Executing task in folder fm-client: npm run styleguide <

> vue-cli-service styleguidist

ℹ ｢wds｣: Project is running at http://localhost:6060/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /Users/rachel/dev/local/fm-client

You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.42.10:6060/

 FAIL  Failed to compile

./src/components/testing/AppButton.vue (./node_modules/vue-styleguidist/lib/loaders/examples-loader.js?customLangs=vue|js|jsx!./src/components/testing/AppButton.vue)
Error: Cannot find module 'acorn'
Require stack:
- /Users/rachel/dev/local/fm-client/node_modules/acorn-dynamic-import/lib/index.js
- /Users/rachel/dev/local/fm-client/node_modules/buble/dist/buble.cjs.js
- /Users/rachel/dev/local/fm-client/node_modules/vue-inbrowser-compiler/lib/vue-inbrowser-compiler.cjs.js
- /Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/loaders/examples-loader.js
- /Users/rachel/dev/local/fm-client/node_modules/loader-runner/lib/loadLoader.js
- /Users/rachel/dev/local/fm-client/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/rachel/dev/local/fm-client/node_modules/webpack/lib/NormalModule.js
- /Users/rachel/dev/local/fm-client/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/rachel/dev/local/fm-client/node_modules/webpack/lib/Compiler.js
- /Users/rachel/dev/local/fm-client/node_modules/webpack/lib/webpack.js
- /Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/scripts/build.js
- /Users/rachel/dev/local/fm-client/node_modules/vue-styleguidist/lib/scripts/index.js
- /Users/rachel/dev/local/fm-client/node_modules/vue-cli-plugin-styleguidist/index.js
- /Users/rachel/dev/local/fm-client/node_modules/@vue/cli-service/lib/Service.js
- /Users/rachel/dev/local/fm-client/node_modules/@vue/cli-service/bin/vue-cli-service.js
 @ ./src/components/testing/AppButton.vue (./node_modules/vue-styleguidist/lib/loaders/vuedoc-loader.js!./src/components/testing/AppButton.vue) 71:15-216
 @ ./node_modules/vue-styleguidist/lib/loaders/styleguide-loader.js!./node_modules/vue-styleguidist/lib/client/index.js
 @ ./node_modules/vue-styleguidist/lib/client/index.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/vue-styleguidist/lib/client/index
./node_modules/markdown-to-jsx/dist/esm.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/markdown-to-jsx/dist'
./node_modules/react-icons/lib/esm/iconBase.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-icons/lib/esm'
./node_modules/react-icons/lib/esm/iconContext.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-icons/lib/esm'
./node_modules/react-simple-code-editor/lib/index.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-simple-code-editor/lib'
./node_modules/react-styleguidist/lib/client/rsg-components/Argument/ArgumentRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Argument'
./node_modules/react-styleguidist/lib/client/rsg-components/Arguments/ArgumentsRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Arguments'
./node_modules/react-styleguidist/lib/client/rsg-components/Code/CodeRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Code'
./node_modules/react-styleguidist/lib/client/rsg-components/Components/Components.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Components'
./node_modules/react-styleguidist/lib/client/rsg-components/Components/ComponentsRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Components'
./node_modules/react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsList.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/ComponentsList'
./node_modules/react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsListRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/ComponentsList'
./node_modules/react-styleguidist/lib/client/rsg-components/Context/Context.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Context'
./node_modules/react-styleguidist/lib/client/rsg-components/Error/ErrorRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Error'
./node_modules/react-styleguidist/lib/client/rsg-components/Examples/Examples.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Examples'
./node_modules/react-styleguidist/lib/client/rsg-components/Examples/ExamplesRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Examples'
./node_modules/react-styleguidist/lib/client/rsg-components/Heading/HeadingRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Heading'
./node_modules/react-styleguidist/lib/client/rsg-components/Link/LinkRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Link'
./node_modules/react-styleguidist/lib/client/rsg-components/Logo/LogoRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Logo'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Markdown.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/BlockquoteRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Blockquote'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/CheckboxRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Checkbox'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Details'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsSummaryRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Details'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Hr/HrRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Hr'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/List/ListRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/List'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/MarkdownHeadingRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Pre/PreRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Pre'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table/TableHeadRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table/TableBodyRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table/TableCellRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table'
./node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRowRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Markdown/Table'
./node_modules/react-styleguidist/lib/client/rsg-components/Name/NameRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Name'
./node_modules/react-styleguidist/lib/client/rsg-components/NotFound/NotFoundRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/NotFound'
./node_modules/react-styleguidist/lib/client/rsg-components/Para/ParaRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Para'
./node_modules/react-styleguidist/lib/client/rsg-components/Pathline/PathlineRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Pathline'
./node_modules/react-styleguidist/lib/client/rsg-components/Playground/Playground.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Playground'
./node_modules/react-styleguidist/lib/client/rsg-components/Playground/PlaygroundRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Playground'
./node_modules/react-styleguidist/lib/client/rsg-components/PlaygroundError/PlaygroundErrorRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/PlaygroundError'
./node_modules/react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponent.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/ReactComponent'
./node_modules/react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponentRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/ReactComponent'
./node_modules/react-styleguidist/lib/client/rsg-components/Ribbon/Ribbon.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Ribbon'
./node_modules/react-styleguidist/lib/client/rsg-components/Ribbon/RibbonRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Ribbon'
./node_modules/react-styleguidist/lib/client/rsg-components/Section/Section.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Section'
./node_modules/react-styleguidist/lib/client/rsg-components/Section/SectionRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Section'
./node_modules/react-styleguidist/lib/client/rsg-components/Sections/Sections.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Sections'
./node_modules/react-styleguidist/lib/client/rsg-components/Sections/SectionsRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Sections'
./node_modules/react-styleguidist/lib/client/rsg-components/Slot/Slot.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Slot'
./node_modules/react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuide.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/StyleGuide'
./node_modules/react-styleguidist/lib/client/rsg-components/Styled/Styled.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Styled'
./node_modules/react-styleguidist/lib/client/rsg-components/TabButton/TabButtonRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/TabButton'
./node_modules/react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContents.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/TableOfContents'
./node_modules/react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContentsRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/TableOfContents'
./node_modules/react-styleguidist/lib/client/rsg-components/Text/TextRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Text'
./node_modules/react-styleguidist/lib/client/rsg-components/ToolbarButton/ToolbarButtonRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/ToolbarButton'
./node_modules/react-styleguidist/lib/client/rsg-components/Type/TypeRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Type'
./node_modules/react-styleguidist/lib/client/rsg-components/Version/VersionRenderer.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/lib/client/rsg-components/Version'
./node_modules/react-styleguidist/node_modules/react-group/index.js
Module not found: Can't resolve 'react' in '/Users/rachel/dev/local/fm-client/node_modules/react-styleguidist/node_modules/react-group'
```

I've spent two full days tweaking my config trying to get vue styleguidist working.  Any suggestions would be greatly appreciated!

**Comment by elevatebart** [comment]
Helo @rachel-flux,

I am so sorry for your lost time, it is really a bumer when things do work according to plan.
The one thing that see that I have not personally tested is the use of the vuetify plugin.

First: You do not need to require webpack config in `styleguide.config.js` if you are using the cli plugin. What you do here is exactly what styleguidist will do by default if you do not mention it.

Second: The "No matching use" error is thrown when there is no rule in the laoder that matches `.vue` files. confer: https://github.com/vuejs/vue-loader/issues/1238

**Comment by elevatebart** [comment]
I just noticed one thing:
In all your scripts you use npx to start the cli like this: `npx vue-cli-service serve`
Why is that?

More importantly, why do you not do that with the styleguidist scripts?
Have you tried it?

Thank you for keeping up with all my questions ;)

**Comment by elevatebart** [comment]
I started this repo, to help debug it together

https://github.com/elevatebart/styleguide-rf

Please fork it and update until we can see the bug.

It looks like you are using a task runner given the first line of each log:

```
> Executing task in folder fm-client: npm run styleguide <
```

Is it the lerna task runner? Is it something local to your repo? This might impact the way the vuecli looks for config.

**Comment by rachel-flux** [comment]
Thanks for the super quick response!

I removed the webpack config in `styleguide.config.js` and updated the styleguidist scripts to use `npx` but unfortunately I am getting the same errors.

I forked the repo you created (thank you!) and when I run it locally, I get an error displayed in the browser: `Error: Cannot find module 'acorn'`

<img width="1064" alt="Screen Shot 2020-05-28 at 12 42 52 PM" src="https://user-images.githubusercontent.com/42042299/83186183-fca4d200-a0e0-11ea-99f3-dbca2c1514e6.png">

So far I haven't made any changes to the forked repo.  Are you seeing this same error?

**Comment by rachel-flux** [comment]
macOS Catalina v10.15
node v13.8.0
linux kernel Darwin 19.0.0 x86_64
GNU bash v3.2.57(1)-release (x86_64-apple-darwin19)
styleguidist v4.23.3

I'm not using lerna.  I think that comment was copy / pasted into my `vue.config.js` from here:
https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/examples/vuecli3-vuetify-ie/vue.config.js

**Comment by elevatebart** [comment]
I should start testing with node 13 and 14 to see what is in store for us. There might be some issues linked to their use. I am going to look into it.

**Comment by elevatebart** [comment]
I just tested with node 13.14.0 and node 14.4.0 and it seems to be working. 
This could be the version of yarn or npm you are using (yarn 2 is not ready for any use yet).

If you have a few min to screenshare, I would be super interrested in seeing what is happening.

Please allow my curiosity ;) come talk on Discord

https://chat.vuejs.org then, I am ElevateBart#1057

**Comment by pgusic** [comment]
Hey guys, did you figure this out?

I'm having the same issue, the Error: Cannot find module 'acorn/dist/walk' 

Any pointers would be great.

**Comment by elevatebart** [comment]
Sometimes, webpack does not resolve the proper version of its dependencies.
Sometimes it simply does not find it.
The dependencies exist in node_modules but webpack looks for it in `node_modules/mod/node_modules/`. because it is the mod package that is calling it.

A solution often worked for me: delete `yarn.lock` + `node_modules` and re-install

**Comment by pgusic** [comment]
Hi elevateBart. 

Deleting yarn.lock and node_modules did not fix the issue for me.

Anything else I can try?

![image](https://user-images.githubusercontent.com/11367551/86376221-f7f6af00-bc86-11ea-9b1f-1946d439ddb2.png)

**Comment by elevatebart** [comment]
Can you share your dependencies and devDependencies?

**Comment by pgusic** [comment]
Sure, take a look please:

![image](https://user-images.githubusercontent.com/11367551/86376744-c29e9100-bc87-11ea-931d-440331bfb076.png)
![image](https://user-images.githubusercontent.com/11367551/86376773-cc27f900-bc87-11ea-9e08-b5e32d7a9b7e.png)

**Comment by pgusic** [comment]
So I got it working right now, removing the acorn from 'resolutions' fixed the issue.

**Comment by elevatebart** [comment]
Do you remember why you had it ?

**Comment by pgusicartisai** [comment]
Some security vulnerability issue 3 months ago. Don't remember what it was exactly.

Anyway thanks for your help!

**Comment by elevatebart** [comment]
You are most welcome!

**Comment by apporoad** [comment]
@elevatebart  I got same problem , and it was just ok after one night...  
anyway thanks for this issue, thanks to @elevatebart
