### ISSUE TITLE
Nuxt template not working?

### ISSUE THREAD

**Issue by dimitrieh** [vue-styleguidist/vue-styleguidist#90]
This is the output I am having. Does this have to do with nuxt being at 1.4?

```
  vue-styleguidist/examples/nuxtjs on master
❯ npm run dev

> styleguide@1.4.9 dev /Users/dimitrie/Projects/vue-styleguidist/examples/nuxtjs
> nuxt

  nuxt:build App root: /Users/dimitrie/Projects/vue-styleguidist/examples/nuxtjs/src +0ms
  nuxt:build Generating /Users/dimitrie/Projects/vue-styleguidist/examples/nuxtjs/.nuxt files... +1ms
  nuxt:build Generating files... +5ms
  nuxt:build Generating routes... +7ms
  nuxt:build Building files... +44ms
  nuxt:build Adding webpack middleware... +2s
  ████████████████████ 100%

Build completed in 5.974s



 DONE  Compiled successfully in -5023ms                                                              23:07:59

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1343:14)
    at listenInCluster (net.js:1391:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1500:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)

npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/Cellar/node/8.5.0/bin/node" "/Users/dimitrie/.node/bin/npm" "run" "dev"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! styleguide@1.4.9 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the styleguide@1.4.9 dev script 'nuxt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the styleguide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs styleguide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls styleguide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dimitrie/Projects/vue-styleguidist/examples/nuxtjs/npm-debug.log
```

**Comment by rafaesc** [comment]
Hi  @dimitrieh,

I tried to replicate this issue, but I couldn't.

I need more details to fix it.

Regards

**Comment by easherma** [comment]
'address in use' to me makes me think you just had another process already running on that port?

**Comment by elevatebart** [comment]
I beleive it is fixed now.
