### ISSUE TITLE
Is native ESM export which import from another module supported?

### ISSUE THREAD

**Issue by jackysee** [vue-styleguidist/vue-styleguidist#911]
Hi, I have some natively (rollup) compiled ESM component that look like this:

`CompA.js`
```
export { _ as default } from "./compA-1234";
```
`compA-1234.js`
```
const comp = {
  render(h) {
    return h("div", this.name);
  },
  props: {
    name: { type: String }
  }
};

export { comp as _ };
```
I tried to set it up but the component seems to be ignored.

`styleguide.config.js`
```
module.exports = {
  components: "src/compA.js"
};
```

**Comment by elevatebart** [comment]
It's a use case that I did not try yet.
I do not think it is hard to make it work.

thank you for reporting

**Comment by elevatebart** [comment]
Hello @jackysee, 
I am looking into your issue right now. 
It seems to be working already.
Would you have a minute to clone the repo linked below and show me what you mean?

https://github.com/vue-styleguidist/vue-styleguidist-example

In extenso: Set-up a component that is ignored

**Comment by jackysee** [comment]
Please try this one
https://github.com/jackysee/vue-styleguidist-example

In this setup, I cannot even get the server started
```
~/Documents/Programs/vue-styleguidist-example master
❯ npm start

> vue-styleguidist@1.0.0 start /Users/jacky/Documents/Programs/vue-styleguidist-example
> vue-styleguidist server

ℹ ｢wds｣: Project is running at http://localhost:6060/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /Users/jacky/Documents/Programs/vue-styleguidist-example

You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.11.45:6060/

Compiling ■■■■■■■■■■■■■■■■                         40%Warning: Error parsing src/components/CompA.js: Error: No suitable component definition found on "/Users/jacky/Documents/Prog"

(node:35763) UnhandledPromiseRejectionWarning: Error: No suitable component definition found on "/Users/jacky/Documents/Programs/vue-styleguidist-example/src/components/CompA.js"
    at Object.<anonymous> (/Users/jacky/Documents/Programs/vue-styleguidist-example/node_modules/vue-docgen-api/dist/parse-script.js:73:31)
    at step (/Users/jacky/Documents/Programs/vue-styleguidist-example/node_modules/vue-docgen-api/dist/parse-script.js:33:23)
    at Object.next (/Users/jacky/Documents/Programs/vue-styleguidist-example/node_modules/vue-docgen-api/dist/parse-script.js:14:53)
    at fulfilled (/Users/jacky/Documents/Programs/vue-styleguidist-example/node_modules/vue-docgen-api/dist/parse-script.js:5:58)
(node:35763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejec)
(node:35763) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process w.
Compiling ■■■■■■■■■■■■■■■■■■■■■■■■■■■■             69%

```

**Comment by elevatebart** [comment]
good catch !! thank you!
