### ISSUE TITLE
Compiling stuck after some time throwing UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by freddy-daniel** [vue-styleguidist/vue-styleguidist#944]
I'm trying to implement styleguidist in my nuxt project

It was working fine, but after adding documentation some more components i got this error

I know this is issue because webpack not loading my components properly

```
You can now view your style guide in the browser:

  Local:            http://localhost:6060/
  On your network:  http://192.168.1.8:6060/

Compiling ■■■■                                     11%(node:3488) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '.mdD:\Projects\test-project\test\components\colorpicker'
    at readdirSync (fs.js:948:3)
    at memoized (D:\Projects\test-project\test\node_modules\lodash\memoize.js:62:23)
    at findFileCaseInsensitive (D:\Projects\test-project\test\node_modules\react-styleguidist\lib\scripts\utils\findFileCaseInsensitive.js:28:17)
    at Object._default [as getExampleFilename] (D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\scripts\schemas\config.js:167:68)
    at processComponent (D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\processComponent.js:49:29)
    at D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\processComponent.js:63:12
    at Array.map (<anonymous>)
    at processComponent (D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\processComponent.js:62:89)
    at D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\getComponents.js:21:45
    at Array.map (<anonymous>)
    at getComponents (D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\getComponents.js:20:21)
    at getSectionComponents (D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\getSections.js:294:40)
    at _callee5$ (D:\Projects\test-project\test\node_modules\vue-styleguidist\lib\loaders\utils\getSections.js:253:28)
    at tryCatch (D:\Projects\test-project\test\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (D:\Projects\test-project\test\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (D:\Projects\test-project\test\node_modules\regenerator-runtime\runtime.js:97:21)
(node:3488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Compiling ■■■■■■■■■■■■■■■■■■■■■■■■■■■■             69%

````

This is my **styleguide.config.js**

```javascript
const { resolve } = require('path');
const { getWebpackConfig } = require('nuxt');

const FILTERED_PLUGINS = [
  'WebpackBarPlugin',
  'VueSSRClientPlugin',
  'HotModuleReplacementPlugin',
  'FriendlyErrorsWebpackPlugin',
  'HtmlWebpackPlugin',
];

const docSiteUrl = process.env.DEPLOY_PRIME_URL;

module.exports = async () => {
	// get the webpack config directly from nuxt
	const nuxtWebpackConfig = await getWebpackConfig('client', {
		for: 'dev',
	});

	const webpackConfig = {
		module: {
			rules: [
				...nuxtWebpackConfig.module.rules.filter(
					// remove the eslint-loader
					a => a.loader !== 'eslint-loader',
				),
			],
		},
		resolve: { ...nuxtWebpackConfig.resolve },
		plugins: [
			...nuxtWebpackConfig.plugins.filter(
				// And some other plugins that could conflcit with ours
				p => FILTERED_PLUGINS.indexOf(p.constructor.name) === -1,
			),
		],
	};

	return {
		components: './components/**/[A-Z]*.vue',
		renderRootJsx: resolve(__dirname, 'styleguide/styleguide.root.js'),
		webpackConfig,
		usageMode: 'expand',
		styleguideDir: 'dist'
	}
};
```

**Comment by freddy-daniel** [comment]
This change in **styleguide.config.js** is resolved my issue

Changed 
`
components: './components/**/[A-Z]*.vue',
`
**into**
`components: './components/**/[A-Za-z]*.vue',`

**Comment by elevatebart** [comment]
you could also say

`./components/**/*.vue` so that all vue components are documented

Simpler, probably clearer.
